spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miniboard?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: Ehdwoddl12

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true